language: ruby

rvm:
  - 1.9.3
  - 2.0.0

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

before_script:
  - bundle install
  - rake app:db:create
  - rake app:db:migrate
  - rake app:db:test:prepare